HOSTS:
  el7-server:
    roles:
      - server
      - default
      - master
      - logstash_server
      - el7
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
    yum_repos:
      logstash:
        #baseurl: 'http://10.255.0.1:8888/'
        baseurl: 'http://packages.elastic.co/logstash/2.3/centos'
        gpgcheck: 0
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/7/$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

  el7-client:
    roles:
      - client
      - agent
      - el7
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
    simp_update_url : https://dl.bintray.com/simp/5.1.X
    yum_repos:
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/7/$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

  el6-server:
    roles:
      - logstash_server
      - el6
    platform:   el-6-x86_64
    box:        puppetlabs/centos-6.6-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant
    yum_repos:
      logstash:
        baseurl: 'http://packages.elastic.co/logstash/2.3/centos'
        #baseurl: 'http://10.255.0.1:8888/'
        gpgcheck: 0
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/6/$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt

  el6-client:
    roles:
      - client
      - agent
      - el6
    platform:   el-6-x86_64
    box:        puppetlabs/centos-6.6-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant
    simp_update_url : https://dl.bintray.com/simp/4.2.X
    yum_repos:
      epel:
        url: 'http://download.fedoraproject.org/pub/epel/6/$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt

CONFIG:
  log_level: verbose
  type:      foss
  vagrant_memsize: 512
  # vb_gui: true
